[package]
name = "mowotion"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
sea-orm = { version = "1.1.2", features = [ "sqlx-sqlite", "runtime-async-std-native-tls", "macros" ] }
